/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum1;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class ukm1 extends javax.swing.JFrame {

    /**
     * Creates new form ukm1
     */
    public ukm1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btniya = new javax.swing.JCheckBox();
        btntidak = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txthp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        combofak = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        btnlaki = new javax.swing.JRadioButton();
        btnperempuan = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaalasan = new javax.swing.JTextArea();
        btnkeluar = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        comboprod = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("FORMULIR PENDAFTARAN UKM-FT ITC");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 380, 20));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 130, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("UNIVERSITAS TRUNOJOYO MADURA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Jl.Raya Telang, PO. BOX 2 Kamal - Bangkalan - Madura");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Telp. (031) 3011146, Fax. (031)  3011506");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\itc100.png")); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 661, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("NAMA LENGKAP                         :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 118, -1, -1));
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 115, 196, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("BERSEDIA                                    :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 165, -1, -1));

        btniya.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btniya.setText("IYA");
        getContentPane().add(btniya, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 163, -1, -1));

        btntidak.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btntidak.setText("TIDAK");
        getContentPane().add(btntidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 163, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("ALAMAT                                      :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 214, -1, -1));

        txtalamat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 211, 196, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("NO.HP                                          :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 265, 217, -1));

        txthp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txthp, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 262, 196, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("PRODI                                          :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 315, 217, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("FAKULTAS                                  :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 367, 217, -1));

        combofak.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        combofak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknik" }));
        getContentPane().add(combofak, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 364, 196, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("JENIS KELAMIN                          :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 416, 217, -1));

        buttonGroup1.add(btnlaki);
        btnlaki.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnlaki.setText("LAKI-LAKI");
        getContentPane().add(btnlaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        buttonGroup1.add(btnperempuan);
        btnperempuan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnperempuan.setText("PEREMPUAN");
        getContentPane().add(btnperempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        areaalasan.setColumns(20);
        areaalasan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        areaalasan.setRows(5);
        jScrollPane1.setViewportView(areaalasan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 466, 196, 141));

        btnkeluar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnkeluar.setText("KELUAR");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, -1, -1));

        btnreset.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnreset.setText("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        btnsimpan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("ALASAN                                       :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 466, 217, -1));

        comboprod.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        comboprod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistem Informasi", "Teknik Informatika", "Teknik Mesin", "Teknik Industri", "Teknik Elektro", "Teknik Mekatro" }));
        getContentPane().add(comboprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 312, 196, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        String fnama = txtnama.getText();
        String falamat = txtalamat.getText();
        String fhp = txthp.getText();
        String selectedOptions = "";
        if (btniya.isSelected()) {
            selectedOptions += "Iya\n";
        }
        if (btntidak.isSelected()) {
            selectedOptions += "tidak\n";
        }
       String selectedOptionsfaku = (String) combofak.getSelectedItem();
       String selectedOptionsprod = (String) comboprod.getSelectedItem();
         if(btnlaki.isSelected()){
             selectedOptions += "Jenis Kelamin : Laki-Laki";    
         }
          if(btnperempuan.isSelected()){
             selectedOptions += "Jenis Kelamin :Perempuan";    
         }
           String falasan = areaalasan.getText();
           //tampilan akhir//
           JOptionPane.showConfirmDialog(null, 
 "Nama : "+fnama+"\n"+
 "Bersedia : "+selectedOptions+"\n"+
 "Alamat : "+falamat+"\n"+
 "nohp : "+fhp+"\n"+
 "fakultas : "+selectedOptionsfaku+"\n"+
 "Prodi : "+selectedOptionsprod+"\n"+
 "Alasan : "+falasan+"\n" 
 , "Data Tersimpan", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
       txtnama.setText("");
 btniya.setSelected(false);
 btntidak.setSelected(false);
 combofak.setSelectedIndex(0); // Mengatur ulang fakultas ke indeks pertama
 comboprod.setSelectedIndex(0); // Mengatur ulang prodi ke indeks pertama
 btnlaki.setSelected(false);
 btnperempuan.setSelected(false);
 txtalamat.setText("");
 txthp.setText("");
 areaalasan.setText("");
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
         int confirmed = JOptionPane.showConfirmDialog(
        this,
        "Apakah Anda yakin ingin keluar dari aplikasi?",
        "Konfirmasi Keluar",
        JOptionPane.YES_NO_OPTION
    );

    if (confirmed == JOptionPane.YES_OPTION) {
        // Menghentikan program secara normal
        System.exit(0);
    
}
    }//GEN-LAST:event_btnkeluarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ukm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ukm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ukm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ukm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ukm1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaalasan;
    private javax.swing.JCheckBox btniya;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JRadioButton btnlaki;
    private javax.swing.JRadioButton btnperempuan;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JCheckBox btntidak;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combofak;
    private javax.swing.JComboBox<String> comboprod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txthp;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
